#! /bin/sh

sxhkd &

# polybar


# compositing and wallpaper 
wal -R &
picom  &
tint2 &
xrdb merge ~/.Xresources &  # (terminal theme)

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         0
bspc config window_gap           18
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 0

# border colors 
bspc config focused_border_color "#8B7C88"
bspc config normal_border_color "#539A96"


